# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Feed me, Jefferson!
authors:
  chefjefferson:
    name: Chef Jefferson
    display_name: Chef Jefferson
    email: headchefjefferson@gmail.com
    github: chefjefferson
  causticpotash:
    name: Sous Chef Karen
    display_name: Karen
    github: causticpotash
  dscheffy:
    name: Dscheffy
    display_name: Dscheffy
    github: dscheffy
description: >- # this means to ignore newlines until "baseurl:"
  This is the Feed me, Jefferson! blog, where we'll document our
  journey of building the Feed me, Jefferson! site and app.
  We're dedicated to helping you (especiall if you're Karen) figure out what
  you're hungry for!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "feedmejefferson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  feedmejefferson
permalink: /:year/:month/:day/:title.html


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
